// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeApp.Data;

#nullable disable

namespace RecipeApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204185826_AddRecipeMetadataColumns")]
    partial class AddRecipeMetadataColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeApp.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Proteins",
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Proteins",
                            Name = "Ground Beef"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Proteins",
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Proteins",
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Proteins",
                            Name = "Tofu"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Vegetables",
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Vegetables",
                            Name = "Carrots"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Vegetables",
                            Name = "Bell Peppers"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Vegetables",
                            Name = "Onions"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Vegetables",
                            Name = "Tomatoes"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Vegetables",
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Vegetables",
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Dairy",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Dairy",
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Dairy",
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Dairy",
                            Name = "Yogurt"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Dairy",
                            Name = "Cream"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Pantry",
                            Name = "Flour"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Pantry",
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Pantry",
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Pantry",
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Pantry",
                            Name = "Soy Sauce"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Pantry",
                            Name = "Vinegar"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Spices",
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Spices",
                            Name = "Black Pepper"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Spices",
                            Name = "Cumin"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Spices",
                            Name = "Paprika"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Spices",
                            Name = "Cinnamon"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Spices",
                            Name = "Oregano"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Fruits",
                            Name = "Apples"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Fruits",
                            Name = "Bananas"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Fruits",
                            Name = "Berries"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Fruits",
                            Name = "Lemons"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Fruits",
                            Name = "Oranges"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Grains",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Grains",
                            Name = "Oats"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Grains",
                            Name = "Quinoa"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Grains",
                            Name = "Brown Rice"
                        });
                });

            modelBuilder.Entity("RecipeApp.Models.SavedRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuggestedAdditionsJson")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SavedRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
